### ISSUE TITLE
Async::Pool::Controller robustness releases resources test randomly fails

### ISSUE THREAD

**Issue by henrich** [socketry/async-pool#9]
I got an error randomly during kick ./spec/async/pool/controller_spec.rb as below.
But rspec with -b option didn't get such error for now.

```ruby
root@tiny:/build/ruby-async-pool-0.3.8# rspec ./spec/async/pool/controller_spec.rb -w
/usr/share/rubygems-integration/all/gems/console-1.10.1/lib/console/logger.rb:57: warning: assigned but unused variable - resolver

Async::Pool::Controller
  #acquire
    can allocate resources
  #release
    will reuse resources
    will retire unusable resources
    will fail when releasing an unacquired resource
    will overflow after freeing 50% of resources
  #prune
    can prune unused resources
  #close
    will no longer be active
    should clear list of available resources
  #to_s
    can inspect empty pool
  with limit
    #to_s
      can inspect empty pool
    #acquire
      will limit allocations
  with non-blocking connect
    #acquire
      can reuse resources
  robustness
    releases resources (FAILED - 1)

Async::Pool::Controller
  #close
    closes all resources when going out of scope

Failures:

  1) Async::Pool::Controller robustness releases resources
     Got 0 failures and 2 other errors:

     1.1) Failure/Error: Async::Task.current.yield

          Async::Stop:
            Async::Stop
          # /usr/share/rubygems-integration/all/gems/async-1.30.1/lib/async/task.rb:66:in `yield'
          # /usr/share/rubygems-integration/all/gems/async-1.30.1/lib/async/reactor.rb:196:in `yield'
          # /usr/share/rubygems-integration/all/gems/async-1.30.1/lib/async/task.rb:108:in `block in yield'
          # /usr/share/rubygems-integration/all/gems/async-1.30.1/lib/async/task.rb:60:in `yield'
          # /usr/share/rubygems-integration/all/gems/async-1.30.1/lib/async/task.rb:108:in `yield'
          # ./spec/async/pool/controller_helper.rb:32:in `viable?'
          # ./lib/async/pool/controller.rb:287:in `get_resource'
          # ./lib/async/pool/controller.rb:275:in `block in available_resource'
          # /usr/share/rubygems-integration/all/gems/async-1.30.1/lib/async/semaphore.rb:80:in `acquire'
          # ./lib/async/pool/controller.rb:274:in `available_resource'
          # ./lib/async/pool/controller.rb:240:in `wait_for_resource'
          # ./lib/async/pool/controller.rb:88:in `acquire'
          # ./spec/async/pool/controller_spec.rb:210:in `block (4 levels) in <top (required)>'
          # /usr/share/rubygems-integration/all/gems/async-1.30.1/lib/async/reactor.rb:340:in `with_timeout'
          # ./spec/async/pool/controller_spec.rb:192:in `block in failures'
          # /usr/share/rubygems-integration/all/gems/async-1.30.1/lib/kernel/sync.rb:29:in `Sync'
          # ./spec/async/pool/controller_spec.rb:189:in `failures'
          # ./spec/async/pool/controller_spec.rb:208:in `block (3 levels) in <top (required)>'
          # /usr/share/rubygems-integration/all/gems/async-rspec-1.16.1/lib/async/rspec/reactor.rb:93:in `block (4 levels) in <module:RSpec>'
          # /usr/share/rubygems-integration/all/gems/async-rspec-1.16.1/lib/async/rspec/reactor.rb:57:in `block in run_in_reactor'
          # /usr/share/rubygems-integration/all/gems/async-1.30.1/lib/async/task.rb:260:in `block in make_fiber'

     1.2) Failure/Error: raise TimeoutError, "Run time exceeded duration #{duration}s:\n#{buffer.string}"

          Async::TimeoutError:
            Run time exceeded duration 10s:
            #<Async::Reactor:0xb2c5b4 1 children (running)>
                #<Async::Task:0xb2c5c8 RSpec::ExampleGroups::AsyncPoolController::Robustness (running)>
                        #<Async::Task:0xb2c5dc Timer task duration=10. (running)>
                        #<Async::Task:0xb2c5f0 running example (running)>
                                #<Async::Task:0xb2c604 transient Async::Pool::Controller Gardener (running)>
          # /usr/share/rubygems-integration/all/gems/async-rspec-1.16.1/lib/async/rspec/reactor.rb:50:in `block in run_in_reactor'
          # /usr/share/rubygems-integration/all/gems/async-1.30.1/lib/async/task.rb:260:in `block in make_fiber'

Finished in 10.29 seconds (files took 0.11287 seconds to load)
14 examples, 1 failure

Failed examples:

rspec ./spec/async/pool/controller_spec.rb:207 # Async::Pool::Controller robustness releases resources
```

**Comment by ioquatix** [comment]
Thanks for reporting this. I will investigate.

**Comment by ioquatix** [comment]
The robustness test is slow and 10s was not sufficient, the current timeout is now 20s which I think is sufficient, but as with all temporal tests, it's more of a wild guess than hard science.
